# Generated by Django 5.1.4 on 2024-12-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='description',
            field=models.CharField(blank=True, max_length=130),
        ),
    ]
