# Generated by Django 5.1.4 on 2024-12-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_advertise_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='contact',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
