# Generated by Django 5.1.4 on 2024-12-18 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0003_advertise_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertise',
            options={'verbose_name_plural': 'Advertise'},
        ),
        migrations.AddField(
            model_name='advertise',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
