# Generated by Django 5.1.4 on 2024-12-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_advertise_contact_advertise_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
