# Generated by Django 5.1.4 on 2024-12-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0003_advertise_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
